apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
    app.kubernetes.io/instance: homeassistant
  name: homeassistant
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: hass
  selector:
    app: homeassistant
  sessionAffinity: None
  type: ClusterIP
